### ISSUE TITLE
Script doesn't replace terms

### ISSUE THREAD

**Issue by Targren** [Luke2642/webui-scripts#1]
The script overrides the batch count, but it doesn't seem to replace the terms. Using the example from the github page

Prompt: car

S/R Batch:  "car, house, tree, frog"  results in the following images:

![00132-3853586036](https://github.com/Luke2642/webui-scripts/assets/11566412/ac0ac13f-7802-4a5b-820f-982e1230941a)
![00133-3853586037](https://github.com/Luke2642/webui-scripts/assets/11566412/3552119e-031b-47c4-a87e-f39fc794477b)
![00134-3853586038](https://github.com/Luke2642/webui-scripts/assets/11566412/2ce0ad04-3ec3-4676-b62d-4f96428556dc)
![00131-3853586035](https://github.com/Luke2642/webui-scripts/assets/11566412/2375ced4-7ef8-48f8-939b-581d536c17f9)

**Comment by Luke2642** [comment]
Sorry, thanks for reporting it... What version of webui are you using? I only tested it on v1.7, running on ubuntu.

Also, may I just sanity check, you didn't include quotes in the box, just the words car, house, tree, frog?

**Comment by Targren** [comment]
Using 1.7, and no, no quotes.

**Comment by Luke2642** [comment]
I'll have a think about what else to debug. 

You completely exited and restarted too, runing webui.bat / webui.sh again? The regular 'restart ui' should be enough though.

**Comment by Targren** [comment]
Yeah, completely terminated and restarted.

**Comment by Luke2642** [comment]
Can you try with 3 words and see if it then generates 3 images? And are you on windows?

Thanks for replying so fast too. It's only 10 lines of code, I'm just stumped!

**Comment by Targren** [comment]
Yeah, I'm on windows 10,  A1111 1.7

Prompt: cat 

If I only use 3 terms ("cat, dog, rabbit"), it generates 3 images

"cat, dog" generates 2. 

"cat, dog, rabbit, otter, alpaca, terrapin" generated 6 

So it's getting the counts right, but they're all cats

**Comment by Luke2642** [comment]
I've got it. Disable dynamic prompts!

**Comment by Targren** [comment]
That was it! Another problem solved by trained professionals.

Thanks!
